version: "3"
services:
  calculator:
    build: .
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis_server
    depends_on:
      - redis_server
  redis_server:
    restart: unless-stopped
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_data:/var/lib/redis/data
volumes:
  redis_data:
